Repository operator-framework/operatorhub.io, pull requests merged in 2019-07, with the labels that each got.

#141 Initial multi stage Dockerfile
  Dockerfile
Labels: size/M

#147 Uploding multi object yaml files
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/components/editor/manfiestUploader/UploaderObjectList.js
  frontend/src/styles/operator-editor-page.scss
Labels: size/L

#148 Uploader styling
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/components/editor/manfiestUploader/UploaderObjectList.js
  frontend/src/components/editor/manfiestUploader/UploaderTypes.js
  frontend/src/pages/operatorBundlePage/bundlePageUtils.js
  frontend/src/styles/operator-editor-page.scss
Labels: size/M

#149 Missing default ALM example for CRD and other bugs
  frontend/src/components/YamlViewer.js
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/manfiestUploader/UploaderObjectList.js
  frontend/src/pages/operatorBundlePage/OperatorCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorOwnedCRDEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorOwnedCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorRequiredCRDEditPage.js
  frontend/src/styles/operator-editor-page.scss
  frontend/src/utils/constants.js
  frontend/src/utils/operatorUtils.js
Labels: size/L

#150 rho-119 added start new bundle button at the top of editor page
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/styles/operator-editor-page.scss
Labels: size/M

#151 rho-120 generated unique js & css bundle names based on content
  frontend/webpack.common.js
Labels: size/S

#152 Splitting script bundle
  frontend/babel.config.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/common/AsyncComponent.js
  frontend/webpack.common.js
  frontend/yarn.lock
  server/package.json
  server/server.js
  server/yarn.lock
Labels: size/XXL

#153 small typo on About page
  frontend/src/pages/documentation/About.js
Labels: size/XS

#155 fixed font preloading and svgs size after
  frontend/src/index.html
  frontend/src/styles/operator-page.scss
Labels: size/XS

#156 DB import shouldn't depend on file names
  server/package-lock.json
  server/package.json
  server/routes/uiRoutes.js
  server/services/loadService.js
  server/utils/operatorUtils.js
  server/yarn.lock
Labels: size/XXL

#158 Sprint3 release
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/common/AsyncComponent.js
  frontend/src/imgs/Capability-Level-Detailed.png
  frontend/src/imgs/capability-level-diagram.svg
  frontend/src/imgs/capability-level-imgs/level-1.svg
  frontend/src/imgs/capability-level-imgs/level-2.svg
  frontend/src/imgs/capability-level-imgs/level-3.svg
  frontend/src/imgs/capability-level-imgs/level-4.svg
  frontend/src/imgs/capability-level-imgs/level-5.svg
  frontend/src/imgs/header-bg.png
  frontend/src/imgs/operator-framework-logo-lite.svg
  frontend/src/imgs/operatorhub-header-logo.svg
  frontend/src/index.html
  frontend/src/styles/operator-page.scss
  frontend/webpack.common.js
  frontend/webpack.dev.js
  server/package-lock.json
  server/package.json
  server/routes/uiRoutes.js
  server/server.js
  server/services/loadService.js
  server/utils/operatorUtils.js
Labels: size/XXL

#160 Parsing kubernetes manifests
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/components/editor/manfiestUploader/UploaderTypes.js
  frontend/src/pages/operatorBundlePage/OperatorCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorDeploymentEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorYamlEditorPage.js
  frontend/src/redux/editorReducer.js
  frontend/src/utils/operatorUtils.js
Labels: size/XL

#161 Rho 161 download button
  frontend/src/components/editor/BundleDownloader.js
  frontend/src/components/editor/forms/OperatorInput.js
  frontend/src/components/editor/forms/OtherFields.js
  frontend/src/components/modals/ConfirmationModal.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/pages/operatorBundlePage/OperatorMetadataPage.js
  frontend/src/pages/operatorBundlePage/OperatorPackagePage.js
  frontend/src/pages/operatorBundlePage/bundlePageUtils.js
  frontend/src/redux/actions/editorActions.js
  frontend/src/redux/confirmationModalReducer.js
  frontend/src/redux/editorReducer.js
  frontend/src/redux/index.js
  frontend/src/utils/operatorTypes.js
  frontend/src/utils/operatorUtils.js
  frontend/webpack.dev.js
Labels: size/XL

#162 Updated styling of editor landing page
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/pages/operatorBundlePage/OperatorEditorSubPage.js
  frontend/src/styles/operator-editor-page.scss
Labels: size/M

#163 Updated install modal to always show prerequisities
  frontend/src/components/modals/InstallModal.js
  frontend/src/styles/operator-page.scss
Labels: size/M

#164 Install texts updates
  frontend/src/components/modals/InstallModal.js
  frontend/src/pages/documentation/HowToInstallOperators.js
Labels: size/S

#165 latest update to install modal style
  frontend/src/components/modals/InstallModal.js
  frontend/src/styles/operator-page.scss
Labels: size/L
