Repository operator-framework/operatorhub.io, pull requests merged in 2019-04, with the labels that each got.

#90 Fix to left align table headers in markdown viewers
  frontend/src/styles/operator-page.scss
Labels: size/XS

#91 Style tables in markdown view better, use safer markdown viewer.
  frontend/package.json
  frontend/src/components/MarkdownView.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/pages/operatorPreviewPage/OperatorPreviewPage.js
  frontend/src/styles/app.scss
  frontend/src/styles/operator-page.scss
  frontend/yarn.lock
Labels: size/L

#92 Adding copy to clipboard for containerImages
  frontend/src/components/OperatorSidePanel.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/operator-page.scss
Labels: size/L

#94 Update operator capability-level-diagram.svg
  frontend/src/imgs/capability-level-diagram.svg
Labels: size/M

#96 Updating import of operatorsidepanel
  frontend/src/pages/operatorPreviewPage/OperatorPreviewPage.js
Labels: size/XS

#98 Use name and version to create the real name in YAML
  frontend/src/components/editor/ManifestUploader.js
  frontend/src/components/editor/ResourcesEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorEditorPage.js
  frontend/src/pages/OperatorEditorPage/OperatorYamlEditorPage.js
  frontend/src/pages/OperatorEditorPage/editorPageUtils.js
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
Labels: size/M

#99 Don't allow generate until all sections have been visited and approved
  frontend/src/components/editor/LabelsEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorEditorPage.js
  frontend/src/pages/OperatorEditorPage/OperatorMetadataPage.js
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
Labels: size/M

#100 Add CRD validation, remove unnecessary fields from Required CRDs
  frontend/src/components/editor/DescriptorsEditor.js
  frontend/src/components/editor/EditorSelect.js
  frontend/src/components/editor/LabelsEditor.js
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/ResourcesEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorCRDEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorCRDsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorMetadataPage.js
  frontend/src/pages/OperatorEditorPage/OperatorOwnedCRDEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorRequiredCRDEditPage.js
  frontend/src/pages/OperatorEditorPage/editorPageUtils.js
  frontend/src/styles/operator-editor-page.scss
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
Labels: size/XXL

#101 Fix button bar styling
  frontend/src/components/editor/EditorSection.js
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorEditorPage.js
  frontend/src/pages/OperatorEditorPage/OperatorEditorSubPage.js
  frontend/src/styles/operator-editor-page.scss
  frontend/src/utils/operatorUtils.js
Labels: size/M

#103 Fix for rebase error in metadata page
  frontend/src/pages/OperatorEditorPage/OperatorMetadataPage.js
Labels: size/XS

#105 Fix list object editor page validation / visuals
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorDeploymentsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorPermissionsPage.js
  frontend/src/styles/operator-editor-page.scss
  frontend/src/utils/operatorDescriptors.js
Labels: size/S
