Repository operator-framework/operatorhub.io, pull requests merged in 2019-03, with the labels that each got.

#75 Fix OLM link
  frontend/src/pages/documenation/HowToInstallOperators.js
Labels: size/XS

#74 Adding operators branch env variable
  build.sh
  server/scripts/update-operators.sh
Labels: size/S

#76 Add Adobe Analytics, remove Coming Soon functions
  comingSoon/imgs/background.png
  comingSoon/imgs/logo.svg
  comingSoon/index.html
  frontend/src/index.html
  frontend/src/pages/documenation/About.js
  frontend/src/utils/documentationLinks.js
  server/routes/uiRoutes.js
  server/utils/constants.js
Labels: size/L

#77 Minor UX fixes on paddings/margins
  frontend/src/imgs/capability-level-diagram.svg
  frontend/src/pages/operatorPage/InstallModal.js
  frontend/src/styles/hub-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/styles/overrides.scss
  frontend/src/styles/page.scss
Labels: size/M

#79 Fix typo in about page
  frontend/src/pages/documenation/About.js
Labels: size/XS

#80 Add Privacy Policy link to footer
  frontend/src/components/Footer.js
  frontend/src/pages/documenation/About.js
Labels: size/M

#81 Add some info & pointers to <noscript> fallback
  frontend/src/index.html
  frontend/src/styles/app.scss
Labels: size/S

#82 Add category selection to hub page
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/redux/index.js
  frontend/src/redux/viewReducer.js
  frontend/src/styles/hub-page.scss
Labels: size/L

#83 Add keywords to search criteria
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/S

#78 Add Operator Preview page
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ConfirmationModal.js
  frontend/src/components/CustomResourceDefinitionsView.js
  frontend/src/components/ExampleYamlModal.js
  frontend/src/components/InstallModal.js
  frontend/src/components/MessageDialog.js
  frontend/src/components/OperatorListItem.js
  frontend/src/components/OperatorSidePanel.js
  frontend/src/components/OperatorTile.js
  frontend/src/components/UploadUrlModal.js
  frontend/src/components/YamlViewer.js
  frontend/src/pages/documentation/About.js
  frontend/src/pages/documentation/Contribute.js
  frontend/src/pages/documentation/GettingStarted.js
  frontend/src/pages/documentation/HowToInstallOperators.js
  frontend/src/pages/documentation/WhatIsAnOperator.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/pages/operatorPreviewPage/OperatorPreviewPage.js
  frontend/src/redux/confirmationModalReducer.js
  frontend/src/redux/index.js
  frontend/src/redux/previewReducer.js
  frontend/src/style.scss
  frontend/src/styles/app.scss
  frontend/src/styles/hub-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/styles/operator-preview-page.scss
  frontend/src/styles/overrides.scss
  frontend/src/styles/variables.scss
  frontend/src/styles/yaml-viewer.scss
  frontend/src/utils/documentationLinks.js
  frontend/src/utils/operatorUtils.js
  frontend/yarn.lock
  server/routes/uiRoutes.js
Labels: size/XXL

#84 Update Preview your CSV text
  frontend/src/pages/documentation/Contribute.js
Labels: size/S

#86 Remove CatalogSource manifest from quick install
  server/services/yamlService.js
Labels: lgtm, size/S

#87 Change Operators to be Channel based
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/InstallModal.js
  frontend/src/components/OperatorSidePanel.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/pages/operatorPreviewPage/OperatorPreviewPage.js
  frontend/src/services/operatorsService.js
  frontend/src/utils/operatorUtils.js
  frontend/yarn.lock
  server/package.json
  server/routes/uiRoutes.js
  server/services/loadService.js
  server/services/operatorsService.js
  server/services/yamlService.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
  server/yarn.lock
Labels: size/XL

#88 Remove catalogsource from globaloperator yaml
  server/services/yamlService.js
Labels: size/M

#89 Fix to accpet strings in operator versions
  server/package.json
  server/utils/operatorUtils.js
  server/yarn.lock
Labels: size/M
