Repository operator-framework/operatorhub.io, pull requests merged in 2019-10, with the labels that each got.

#204 recover from missing object in multi document yaml
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
Labels: size/S

#205 support cr template without use of filename
  frontend/src/components/editor/descriptors/DescriptorsEditor.js
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDEditPage.js
  frontend/src/utils/operatorTypes.js
Labels: size/L

#206 Show loader for async components
  frontend/src/common/AsyncComponent.js
  frontend/src/components/other/ErrorMessage.js
  frontend/src/components/other/Loader.js
  frontend/src/components/page/Page.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
Labels: size/L

#207 Don't reload landing page
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/redux/operatorsReducer.js
Labels: size/M

#209 Bash is required to run this script, not sh
  server/scripts/update-operators.sh
Labels: size/XS

#213 failing upload in special cases
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
Labels: size/S

#216 release bug fix
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
Labels: size/S

#217 categories are lost on landing page after operator detail is shown
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/redux/operatorsReducer.js
  frontend/src/services/operatorsService.js
Labels: size/M

#219 released to prod
  frontend/src/pages/documentation/Contribute.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/redux/operatorsReducer.js
  frontend/src/services/operatorsService.js
Labels: size/M

#220 Testing nested community repo in dev
  server/scripts/update-operators.sh
Labels: size/XS

#221 Revert "Testing nested community repo in dev"
  server/scripts/update-operators.sh
Labels: size/XS

#224 Crd lost after uploading
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
Labels: size/XS

#226 Server health endpoint
  server/routes/apiRoutes.js
Labels: size/XS
