Repository operator-framework/operatorhub.io, pull requests merged in 2019-05, with the labels that each got.

#107 frontend/src: fix Contribute page text and examples
  frontend/src/pages/documentation/Contribute.js
  frontend/src/utils/documentationLinks.js
Labels: size/L

#111 Add eslint to server
  README.md
  frontend/src/components/OperatorSidePanel.js
  package.json
  server/package.json
  server/yarn.lock
Labels: size/XXL

#112 Update Contribute doc Test your Operator section
  frontend/src/pages/documentation/Contribute.js
  frontend/src/utils/documentationLinks.js
Labels: size/M

#113 Rebase dev
  README.md
  frontend/src/components/OperatorSidePanel.js
  frontend/src/pages/documentation/Contribute.js
  frontend/src/utils/documentationLinks.js
  package.json
  server/package.json
  server/yarn.lock
Labels: size/XXL

#95 Update capability level diagram url in operator-sdk
  frontend/src/utils/documentationLinks.js
Labels: size/XS

#114 stable links to latest operator version
  .gitattributes
  frontend/src/pages/operatorHub/OperatorHub.js
  server/services/operatorsService.js
  server/store/persistentStore.js
Labels: size/L

#109 Editor: change UI state to reflect the result of pre-population
  .gitattributes
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/ManifestUploader.js
  frontend/src/pages/OperatorEditorPage/OperatorClusterPermissionsEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorClusterPermissionsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorDeploymentEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorDeploymentsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorInstallModesPage.js
  frontend/src/pages/OperatorEditorPage/OperatorMetadataPage.js
  frontend/src/pages/OperatorEditorPage/OperatorOwnedCRDEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorOwnedCRDsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorPermissionsEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorPermissionsPage.js
  frontend/src/pages/OperatorEditorPage/OperatorRequiredCRDEditPage.js
  frontend/src/pages/OperatorEditorPage/OperatorRequiredCRDsPage.js
  frontend/src/pages/OperatorEditorPage/editorPageUtils.js
  frontend/src/redux/index.js
Labels: size/L

#117 Install modal produce install path without version
  frontend/src/components/InstallModal.js
  server/services/yamlService.js
  server/utils/operatorUtils.js
Labels: size/L

#120 Description is edited in separate sections instead of single one
  frontend/src/components/editor/DescriptionEditor.js
  frontend/src/components/editor/MarkdownEditor.js
  frontend/src/pages/OperatorEditorPage/OperatorMetadataPage.js
  frontend/src/pages/OperatorEditorPage/editorPageUtils.js
  frontend/src/styles/operator-editor-page.scss
  frontend/src/utils/constants.js
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
Labels: size/L

#119 Added example deployment to operator defaults
  frontend/src/utils/operatorUtils.js
Labels: size/M

#118 Added link to preview operator in Contribute menu
  frontend/src/components/HeaderTopBar.js
Labels: size/S

#121 Update Bundle Page text to clarify what to upload and purpose of the page
  frontend/src/App.js
  frontend/src/components/editor/EditorSection.js
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/ManifestUploader.js
  frontend/src/components/page/HeaderTopBar.js
  frontend/src/pages/OperatorEditorPage/OperatorEditorPage.js
  frontend/src/pages/OperatorEditorPage/OperatorYamlEditorPage.js
  frontend/src/pages/documentation/Contribute.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/pages/operatorBundlePage/OperatorCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorClusterPermissionsEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorClusterPermissionsPage.js
  frontend/src/pages/operatorBundlePage/OperatorDeploymentEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorDeploymentsPage.js
  frontend/src/pages/operatorBundlePage/OperatorEditorSubPage.js
  frontend/src/pages/operatorBundlePage/OperatorInstallModesPage.js
  frontend/src/pages/operatorBundlePage/OperatorMetadataPage.js
  frontend/src/pages/operatorBundlePage/OperatorOwnedCRDEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorOwnedCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorPermissionsEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorPermissionsPage.js
  frontend/src/pages/operatorBundlePage/OperatorRequiredCRDEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorRequiredCRDsPage.js
  frontend/src/pages/operatorBundlePage/OperatorYamlEditorPage.js
  frontend/src/pages/operatorBundlePage/bundlePageUtils.js
  frontend/src/utils/documentationLinks.js
  frontend/src/utils/operatorUtils.js
  server/routes/uiRoutes.js
Labels: size/XL

#123 Dev to master
  .gitattributes
  frontend/src/components/HeaderTopBar.js
  frontend/src/components/InstallModal.js
  frontend/src/pages/operatorHub/OperatorHub.js
  server/services/operatorsService.js
  server/services/yamlService.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/L

#124 Editor validation fix
  frontend/src/components/editor/DescriptorsEditor.js
  frontend/src/components/editor/ResourcesEditor.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/pages/operatorBundlePage/OperatorDeploymentsPage.js
  frontend/src/pages/operatorBundlePage/OperatorOwnedCRDEditPage.js
  frontend/src/pages/operatorBundlePage/OperatorPermissionsPage.js
  frontend/src/pages/operatorBundlePage/OperatorRequiredCRDEditPage.js
  frontend/src/pages/operatorBundlePage/bundlePageUtils.js
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
Labels: size/L

#122 Compare uploaded manifest against default operator
  frontend/src/components/editor/ManifestUploader.js
Labels: size/S

#116 Operator courier used to migrate operators to nested structure
  build.sh
  server/scripts/update-operators.sh
  server/services/loadService.js
  server/utils/constants.js
  server/utils/operatorUtils.js
Labels: size/M
