Repository operator-framework/operatorhub.io, pull requests merged in 2019-12, with the labels that each got.

#234 Update contribute page with nested folder structure and table content
  frontend/src/pages/documentation/Contribute.tsx
  frontend/src/styles/documentation-page.scss
  frontend/src/utils/documentationLinks.ts
Labels: size/M

#236 released contribute changes
  frontend/src/pages/documentation/Contribute.tsx
  frontend/src/styles/documentation-page.scss
  frontend/src/utils/documentationLinks.ts
Labels: size/M

#237 Dockerfile: added dockerize and fixed entrypoint, passing args from e…
  Dockerfile
  server/bin/uid_entrypoint
Labels: size/XS

#238 Rho 434 package channels editor
  frontend/src/App.tsx
  frontend/src/components/editor/EditorSection.tsx
  frontend/src/components/editor/ListObjectEditor.tsx
  frontend/src/components/modals/UploadPackageFromGithubModal.tsx
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannel.tsx
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannelIcon.tsx
  frontend/src/components/packageEditor/channelsEditor/EditNameModal.tsx
  frontend/src/components/page/HeaderTopBar.tsx
  frontend/src/components/uploader/operator/OperatorVersionUploader.tsx
  frontend/src/components/uploader/operator/UploaderUtils.ts
  frontend/src/components/uploader/package/PackageUploader.tsx
  frontend/src/components/uploader/package/PackageUploaderDropArea.tsx
  frontend/src/components/uploader/package/PackageUploaderObjectList.tsx
  frontend/src/pages/documentation/Contribute.tsx
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.tsx
  frontend/src/pages/operatorBundlePage/OperatorInstallModesPage.tsx
  frontend/src/pages/operatorBundlePage/OperatorMetadataPage.tsx
  frontend/src/pages/operatorBundlePage/OperatorPackagePage.js
  frontend/src/pages/operatorBundlePage/OperatorYamlEditorPage.tsx
  frontend/src/pages/operatorBundlePage/bundlePageUtils.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorCRDsPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDEditPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDsPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorRequiredCRDEditPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorRequiredCRDsPage.tsx
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentEditPage.tsx
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentsPage.js
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentsPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorClusterPermissionsEditPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorClusterPermissionsPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorPermissionsEditPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorPermissionsPage.tsx
  frontend/src/pages/operatorBundlePage/subPage/EditorBreadCrumbs.tsx
  frontend/src/pages/operatorBundlePage/subPage/EditorButtonBar.tsx
  frontend/src/pages/operatorBundlePage/subPage/OperatorEditorSubPage.tsx
  frontend/src/pages/operatorPage/OperatorPage.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/pages/packageEditor/PackageEditorLandingPage.tsx
  frontend/src/pages/packageEditor/pageWrapper/PackageEditorBreadcrumbs.tsx
  frontend/src/pages/packageEditor/pageWrapper/PackageEditorPageWrapper.tsx
  frontend/src/redux/actions/editorActions.ts
  frontend/src/redux/actions/packageEditorActions.ts
  frontend/src/redux/editorAutosave.ts
  frontend/src/redux/editorReducer.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/styles/package-editor.scss
  frontend/src/utils/constants.ts
  frontend/src/utils/operatorUtils.ts
  frontend/src/utils/operatorValidators.ts
  frontend/src/utils/packageEditorTypes.tsx
  frontend/webpack.dev.js
  server/package.json
Labels: size/XXL

#239 rho-158 assembled package zip for download from data model
  frontend/package.json
  frontend/src/components/packageEditor/createPackage/CreateNewPackageSection.tsx
  frontend/src/components/uploader/operator/OperatorVersionUploader.tsx
  frontend/src/components/uploader/package/PackageUploader.tsx
  frontend/src/index.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/pages/packageEditor/PackageEditorLandingPage.tsx
  frontend/src/redux/actions/editorActions.ts
  frontend/src/redux/actions/index.ts
  frontend/src/redux/actions/packageEditorActions.ts
  frontend/src/redux/editorAutosave.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/redux/store.ts
  frontend/src/styles/package-editor.scss
  frontend/src/utils/constants.ts
  frontend/src/utils/operatorValidators.ts
  frontend/src/utils/packageEditorTypes.tsx
Labels: size/L

#240 rho-512 Editing version in package definition editor
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannel.tsx
  frontend/src/components/packageEditor/createPackage/CreateNewPackageSection.tsx
  frontend/src/components/packageEditor/modals/EditChannelNameModal.tsx
  frontend/src/components/packageEditor/modals/EditNameModal.tsx
  frontend/src/components/packageEditor/modals/EditVersionNameModal.tsx
  frontend/src/components/uploader/package/PackageUploaderObjectList.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/redux/actions/confirmationModalActions.ts
  frontend/src/redux/actions/packageEditorActions.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/styles/package-editor.scss
  frontend/src/utils/operatorValidators.ts
Labels: size/XL

#241 released hotfix for install modal
  frontend/src/components/modals/InstallModal.tsx
Labels: size/M

#243 updated deps to resolve security vulnerability
  frontend/package-lock.json
  frontend/package.json
Labels: size/XXL

#244 Rho 513 channel validation
  frontend/src/App.tsx
  frontend/src/components/editor/EditorSection.tsx
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannel.tsx
  frontend/src/components/page/HeaderTopBar.tsx
  frontend/src/components/uploader/operator/OperatorVersionUploader.tsx
  frontend/src/components/uploader/operator/UploaderUtils.ts
  frontend/src/components/uploader/package/PackageUploader.tsx
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.tsx
  frontend/src/pages/operatorBundlePage/OperatorMetadataPage.tsx
  frontend/src/pages/operatorBundlePage/bundlePageUtils.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorCRDsPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDEditPage.tsx
  frontend/src/pages/operatorBundlePage/crds/OperatorRequiredCRDEditPage.tsx
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentEditPage.tsx
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentsPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorPermissionsEditPage.tsx
  frontend/src/pages/operatorBundlePage/permissions/OperatorPermissionsPage.tsx
  frontend/src/pages/operatorBundlePage/subPage/OperatorEditorSubPage.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/pages/packageEditor/PackageEditorLandingPage.tsx
  frontend/src/redux/actions/confirmationModalActions.ts
  frontend/src/redux/actions/editorActions.ts
  frontend/src/redux/actions/packageEditorActions.ts
  frontend/src/redux/editorReducer.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/styles/package-editor.scss
  frontend/src/utils/constants.ts
  frontend/src/utils/operatorUtils.ts
  frontend/src/utils/packageEditorTypes.tsx
  frontend/src/utils/packageEditorUtils.ts
Labels: size/XL

#245 rho-522 added persistance of edited operator version into local storage
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.tsx
  frontend/src/pages/operatorBundlePage/bundlePageUtils.tsx
  frontend/src/pages/operatorBundlePage/subPage/EditorBreadCrumbs.tsx
  frontend/src/pages/operatorBundlePage/subPage/OperatorEditorSubPage.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/pages/packageEditor/pageWrapper/PackageEditorBreadcrumbs.tsx
  frontend/src/redux/editorAutosave.ts
  frontend/src/redux/editorReducer.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/utils/constants.ts
  frontend/src/utils/operatorUtils.ts
  frontend/src/utils/operatorValidation.ts
  frontend/src/utils/operatorValidators.ts
  frontend/src/utils/packageEditorUtils.ts
Labels: size/L

#246 rho-523 show error when no content downloaded
  frontend/src/components/modals/UploadPackageFromGithubModal.tsx
  frontend/src/components/uploader/operator/OperatorVersionUploader.tsx
Labels: size/M

#247 rho-521 fixed version rename bug no.2
  frontend/src/components/modals/UploadPackageFromGithubModal.tsx
  frontend/src/components/packageEditor/createPackage/CreateNewPackageSection.tsx
  frontend/src/components/packageEditor/modals/EditNameModal.tsx
  frontend/src/components/uploader/package/PackageUploader.tsx
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.tsx
  frontend/src/pages/operatorBundlePage/bundlePageUtils.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/pages/packageEditor/PackageEditorLandingPage.tsx
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/utils/packageEditorTypes.tsx
  frontend/src/utils/packageEditorUtils.ts
Labels: size/L

#248 rho-527-fixed-duplicate-version-issues
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDEditPage.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
Labels: size/M

#251 Rendering Update path for skips and skip range
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannel.tsx
  frontend/src/components/packageEditor/channelsEditor/VersionUpdatePath.tsx
  frontend/src/components/packageEditor/modals/EditUpdateGraphModal.tsx
  frontend/src/components/uploader/package/PackageUploader.tsx
  frontend/src/styles/package-editor.scss
  frontend/src/utils/operatorTypes.ts
  frontend/src/utils/packageEditorTypes.tsx
Labels: size/L

#252 rho-525 created update graph modla and logic
  frontend/package.json
  frontend/src/components/editor/forms/OperatorSelect.tsx
  frontend/src/components/packageEditor/channelsEditor/ChannelEditorChannel.tsx
  frontend/src/components/packageEditor/modals/EditUpdateGraphModal.tsx
  frontend/src/pages/packageEditor/PackageChannelsEditor.tsx
  frontend/src/redux/actions/packageEditorActions.ts
  frontend/src/redux/packageEditorReducer.ts
  frontend/src/styles/overrides.scss
Labels: size/XL
