Repository operator-framework/operatorhub.io, pull requests merged in 2019-09, with the labels that each got.

#186 Dockerfile: moving to UBI8 and fixes using non-root in OpenShift
  Dockerfile
  server/bin/uid_entrypoint
Labels: size/M

#189 Automatically update OLM version in install modal
  frontend/src/components/InternalLink.js
  frontend/src/components/modals/InstallModal.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/redux/index.js
  frontend/src/redux/operatorsReducer.js
  frontend/src/services/operatorsService.js
Labels: size/L

#190 feedback link to bundle editor page
  frontend/src/components/ExternalLink.js
  frontend/src/components/modals/InstallModal.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
Labels: size/S

#192 new issue link update
  frontend/src/components/editor/LabelsEditor.js
  frontend/src/components/editor/forms/OperatorInput.js
  frontend/src/components/editor/forms/OperatorInputUncontrolled.js
  frontend/src/components/editor/forms/OperatorTextArea.js
  frontend/src/components/editor/forms/OperatorTextAreaUncontrolled.js
  frontend/src/components/modals/ImportYamlModal.js
  frontend/src/pages/operatorBundlePage/OperatorBundlePage.js
  frontend/src/pages/operatorBundlePage/OperatorEditorSubPage.js
  frontend/src/pages/operatorBundlePage/deployments/OperatorDeploymentEditPage.js
  frontend/src/utils/documentationLinks.js
  frontend/src/utils/operatorDescriptors.js
  frontend/src/utils/operatorUtils.js
  frontend/src/utils/operatorValidators.js
Labels: size/XL

#194 removed category options from keywords select
  frontend/src/pages/operatorBundlePage/OperatorMetadataPage.js
Labels: size/XS

#195 smart operator objects merging on upload
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
  frontend/src/utils/operatorTypes.js
  frontend/src/utils/operatorUtils.js
Labels: size/L

#199 crd descriptor reordering issues
  frontend/src/components/editor/ListObjectEditor.js
  frontend/src/components/editor/descriptors/DescriptorsEditor.js
  frontend/src/components/editor/manfiestUploader/UploaderUtils.js
  frontend/src/pages/operatorBundlePage/bundlePageUtils.js
  frontend/src/pages/operatorBundlePage/crds/OperatorOwnedCRDEditPage.js
  frontend/src/utils/operatorTypes.js
  frontend/src/utils/operatorUtils.js
Labels: size/L

#198 Dockerfile refactored, multi stage dropped
  Dockerfile
Labels: size/M

#200 Release nested operator structure support
  Dockerfile
  server/services/loadService.js
Labels: size/L

#201 Added missing Dockerfile entrypoint
  server/bin/uid_entrypoint
Labels: size/XS

#202 Parse version from crd versions
  frontend/src/components/editor/manfiestUploader/ManifestUploader.js
Labels: size/XS
