Repository operator-framework/operatorhub.io, pull requests merged in 2019-02, with the labels that each got.

#12 Tweak hover state styling for Card and List Item
  src/styles/hub-page.scss
Labels: size/S

#13 Use live search on index page
  src/components/HeaderTopBar.js
  src/pages/operatorHub/HubHeader.js
  src/pages/operatorHub/OperatorHub.js
Labels: size/S

#11 Add Initial Footer
  src/components/Footer.js
  src/components/Header.js
  src/components/HeaderTopBar.js
  src/imgs/operator-framework-logo-lite.svg
  src/pages/operatorHub/HubHeader.js
  src/pages/operatorHub/OperatorHub.js
  src/pages/operatorPage/OperatorHeader.js
  src/pages/operatorPage/OperatorPage.js
  src/services/operatorsService.js
  src/style.scss
  src/styles/app.scss
  src/styles/footer.scss
  src/styles/header.scss
  src/styles/operator-page.scss
  src/styles/overrides.scss
Labels: size/XL

#14 Small fix to prevent header background diff between views
  src/styles/header.scss
Labels: size/XS

#15 Set details page breadcrumbs to be pinned under the header
  src/pages/operatorHub/HubHeader.js
  src/pages/operatorPage/OperatorPage.js
  src/services/operatorsService.js
  src/styles/app.scss
  src/styles/footer.scss
  src/styles/header.scss
  src/styles/operator-page.scss
  src/styles/variables.scss
Labels: size/L

#16 Update to show container image as link and categories in details
  src/components/ExternalLink.js
  src/pages/operatorHub/OperatorHub.js
  src/pages/operatorPage/OperatorPage.js
  src/utils/operatorUtils.js
Labels: size/L

#18 SDK btn-text tweak
  src/components/Footer.js
Labels: size/XS

#20 Refactor pages to use common Page which handles scrolling
  frontend/src/components/HeaderTopBar.js
  frontend/src/components/Page.js
  frontend/src/pages/operatorHub/HubHeader.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorHeader.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/services/operatorsService.js
  frontend/src/styles/header.scss
  frontend/src/styles/hub-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/utils/operatorUtils.js
  server/services/operatorsService.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/XL

#5 For prototype deployment
  README.md
  build.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.html
  package.json
  run.sh
  server/data/.gitkeep
  server/package-lock.json
  server/scripts/update-operators.sh
  server/server.js
  server/services/loadService.js
Labels: size/XXL

#24 Making repo env variable + updating package.json
  .gitignore
  build.sh
  frontend/package.json
Labels: size/M

#21 Add Getting Started page
  frontend/src/App.js
  frontend/src/components/ExternalLink.js
  frontend/src/components/Footer.js
  frontend/src/components/HeaderTopBar.js
  frontend/src/components/Page.js
  frontend/src/imgs/Operator-Maturity-Detailed.png
  frontend/src/pages/gettingStarted/GettingStarted.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/style.scss
  frontend/src/styles/app.scss
  frontend/src/styles/getting-started.scss
  frontend/src/styles/header.scss
Labels: size/XL

#22 Correct sorting on maturity filters
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/styles/overrides.scss
Labels: size/M

#23 Fix routing to handle bookmarking of filters / view settings
  frontend/package.json
  frontend/src/App.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/redux/index.js
  frontend/src/redux/viewReducer.js
  frontend/yarn.lock
Labels: size/L

#25 Add documentation pages
  frontend/src/App.js
  frontend/src/components/DocumentationPage.js
  frontend/src/components/Footer.js
  frontend/src/components/HeaderTopBar.js
  frontend/src/components/MarkdownView.js
  frontend/src/components/Page.js
  frontend/src/components/SocialMediaLinks.js
  frontend/src/pages/contribute/Contribute.js
  frontend/src/pages/gettingStarted/GettingStarted.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/pages/whatIsAnOperator/WhatIsAnOperator.js
  frontend/src/style.scss
  frontend/src/styles/app.scss
  frontend/src/styles/documentation-page.scss
  frontend/src/styles/footer.scss
  frontend/src/styles/getting-started.scss
  frontend/src/styles/header.scss
  frontend/src/styles/hub-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/styles/overrides.scss
  frontend/src/styles/page.scss
  frontend/src/utils/documentationLinks.js
  frontend/yarn.lock
  server/scripts/update-operators.sh
Labels: size/XXL

#28 Pakcage-lock.json update
  build.sh
  frontend/package-lock.json
Labels: size/XXL

#30 UI Fixes
  frontend/src/components/DocumentationPage.js
  frontend/src/components/Footer.js
  frontend/src/components/Page.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/app.scss
  frontend/src/styles/page.scss
  frontend/src/utils/documentationLinks.js
  server/utils/operatorUtils.js
Labels: size/L

#32 Use path rather that query params for operator details page
  frontend/src/App.js
  frontend/src/__mock__/operators.js
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/services/operatorsService.js
  frontend/webpack.dev.js
  server/routes/uiRoutes.js
  server/server.js
Labels: size/XL

#31 Update coming soon date/time to Feb 28th 10AM PST
  comingSoon/index.html
Labels: size/XS

#33 Add akamai sureroute test
  server/routes/uiRoutes.js
  test-route/akamai-sureroute-test-object.html
Labels: size/L

#34 Add CRD tiles and Example YAML viewer.
  frontend/package.json
  frontend/src/components/YamlViewer.js
  frontend/src/pages/operatorPage/ExampleYamlModal.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/app.scss
  frontend/src/styles/operator-page.scss
  frontend/yarn.lock
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/XXL

#35 Update footer link, handle operators with different display names per…
  frontend/src/components/Footer.js
  frontend/src/utils/documentationLinks.js
  frontend/src/utils/operatorUtils.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/M

#44 Show mouse cursor as pointer for operator capability popover icon and styling
  comingSoon/index.html
  frontend/src/index.html
  frontend/src/styles/operator-page.scss
  frontend/src/styles/overrides.scss
Labels: size/S

#41 Updates to improve header collapse
  frontend/src/components/DocumentationPage.js
  frontend/src/components/HeaderTopBar.js
  frontend/src/components/InternalLink.js
  frontend/src/components/Page.js
  frontend/src/styles/documentation-page.scss
  frontend/src/styles/hub-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/styles/page.scss
  frontend/src/styles/variables.scss
Labels: size/L

#45 Add Install popup content, how to install page, install yaml generator.
  frontend/src/App.js
  frontend/src/pages/documenation/About.js
  frontend/src/pages/documenation/Contribute.js
  frontend/src/pages/documenation/GettingStarted.js
  frontend/src/pages/documenation/HowToInstallOperators.js
  frontend/src/pages/documenation/WhatIsAnOperator.js
  frontend/src/pages/operatorPage/InstallModal.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/app.scss
  frontend/src/styles/documentation-page.scss
  frontend/src/styles/operator-page.scss
  frontend/src/styles/overrides.scss
  frontend/src/styles/vendor.scss
  frontend/src/utils/documentationLinks.js
  server/routes/apiRoutes.js
  server/routes/uiRoutes.js
  server/services/loadService.js
  server/services/operatorsService.js
  server/services/yamlService.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/L

#46 Fix search, sort providers alphabetically
  frontend/src/pages/operatorHub/OperatorHub.js
Labels: size/S

#48 Add mobile filters on hub page
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/styles/hub-page.scss
Labels: size/L

#47 Update documentation pages to latest edits of the docs
  frontend/src/pages/documenation/About.js
  frontend/src/pages/documenation/Contribute.js
  frontend/src/pages/documenation/GettingStarted.js
  frontend/src/pages/documenation/WhatIsAnOperator.js
  frontend/src/utils/documentationLinks.js
Labels: size/L

#50 Handle subroutes for ComingSoon
  server/routes/uiRoutes.js
Labels: size/XS

#51 Read from upstream-community-operators only, env to set directory
  server/services/loadService.js
  server/utils/constants.js
Labels: size/XS

#52 Install modal fixup, add copy install command function
  frontend/src/pages/documenation/HowToInstallOperators.js
  frontend/src/pages/operatorPage/InstallModal.js
  frontend/src/styles/operator-page.scss
Labels: size/L

#49 Change Markdown view component, fixes iOS chrome scrolling issue
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MarkdownView.js
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/operator-page.scss
  frontend/yarn.lock
Labels: size/XXL

#53 Show coming soon page until release date (unless overriden by env)
  comingSoon/index.html
  server/routes/uiRoutes.js
  server/utils/constants.js
Labels: size/M

#54 Remove service-worker
  frontend/src/index.js
  frontend/src/registerServiceWorker.js
Labels: size/L

#55 Determine URL for install command based on current URL
  frontend/src/pages/operatorPage/InstallModal.js
Labels: size/XS

#56 Fix for Contribute dropdown overwrite by toolbar
  frontend/src/styles/page.scss
Labels: size/XS

#57 Fix formatting of generated install YAML
  server/services/yamlService.js
Labels: size/M

#58 Minor visual changes to hub page view bar
  frontend/src/pages/operatorHub/OperatorHub.js
  frontend/src/styles/hub-page.scss
Labels: size/M

#59 Fix for invalid operator ID retrievals
  server/store/persistentStore.js
Labels: size/XS

#60 Fix for DEV mode refresh of operators page
  frontend/webpack.dev.js
Labels: size/S

#61 Update release date/time to Feb 28, 2019 9:00:00 PST
  comingSoon/index.html
  server/utils/constants.js
Labels: size/XS

#62 Update OLM install command, add Copy to clipboard for it
  frontend/src/pages/operatorPage/InstallModal.js
Labels: size/M

#63 Fix for install modal at mobile resolutions
  frontend/src/styles/operator-page.scss
Labels: size/XS

#64 UX fixes for paddings and fixed toolbar
  frontend/src/components/Page.js
  frontend/src/styles/operator-page.scss
  frontend/src/styles/page.scss
  frontend/src/styles/variables.scss
Labels: size/S

#65 Fix YAML output for install command
  server/services/yamlService.js
Labels: size/M

#66 Update HowToInstall page with permissions section
  frontend/src/pages/documenation/HowToInstallOperators.js
Labels: size/S

#67 Fix double scroll bar issue in details
  frontend/src/pages/operatorPage/OperatorPage.js
  frontend/src/styles/operator-page.scss
  frontend/src/styles/page.scss
Labels: size/M

#68 Handle Global Operator install
  frontend/src/pages/documenation/HowToInstallOperators.js
  frontend/src/pages/operatorPage/InstallModal.js
  frontend/src/styles/app.scss
  frontend/src/styles/operator-page.scss
  frontend/src/utils/documentationLinks.js
  server/services/yamlService.js
  server/store/persistentStore.js
  server/utils/operatorUtils.js
Labels: size/L

#69 util: update upstream directory
  frontend/src/utils/documentationLinks.js
Labels: size/XS

#70 Fix apiVersion for global operator install
  server/services/yamlService.js
Labels: size/XS

#71 Ensure release date on client and server are the same
  comingSoon/index.html
  server/routes/apiRoutes.js
Labels: size/M

#72 Update to 'How does OperatorHub.io work'
  frontend/src/pages/documenation/About.js
Labels: size/S
